"""b6 production history and waste records

Revision ID: 0ab7ad51d7a1
Revises: 376fcbee2302
Create Date: 2026-08-31 01:59:54.765491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ab7ad51d7a1'
down_revision: Union[str, None] = '376fcbee2302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_records',
    sa.Column('production_order_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('waste_type', sa.String(length=40), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('recoverable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('production_orders', sa.Column('operator', sa.String(length=120), nullable=True))
    op.add_column('production_orders', sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('downtime_minutes', sa.Float(), nullable=True))
    op.add_column('production_orders', sa.Column('avg_micron', sa.Float(), nullable=True))
    # server_default: mevcut satırlar için NOT NULL JSON sütunu, aynı B.1-B.5
    # migration'larındaki SQLite kısıtı — bkz. app/models/production.py notu.
    op.add_column(
        'production_orders',
        sa.Column('actual_layer_ratios', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'actual_layer_ratios')
    op.drop_column('production_orders', 'avg_micron')
    op.drop_column('production_orders', 'downtime_minutes')
    op.drop_column('production_orders', 'actual_end')
    op.drop_column('production_orders', 'actual_start')
    op.drop_column('production_orders', 'operator')
    op.drop_table('waste_records')
    # ### end Alembic commands ###
