"""b7 cost factor library

Revision ID: 0bf0280c7ea2
Revises: 0ab7ad51d7a1
Create Date: 2026-08-31 02:06:03.341728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bf0280c7ea2'
down_revision: Union[str, None] = '0ab7ad51d7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_factors',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('electricity_rate', sa.Float(), nullable=True),
    sa.Column('gas_rate', sa.Float(), nullable=True),
    sa.Column('labor_rate', sa.Float(), nullable=True),
    sa.Column('waste_disposal_cost', sa.Float(), nullable=True),
    sa.Column('recovery_cost', sa.Float(), nullable=True),
    sa.Column('machine_hour_rate', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_factors')
    # ### end Alembic commands ###
