"""h2_asama9_uretim_emri_zenginlestirme

Revision ID: 153414c62991
Revises: 6afb147f493c
Create Date: 2026-09-01 02:14:57.224907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '153414c62991'
down_revision: Union[str, None] = '6afb147f493c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('order_no', sa.String(length=40), nullable=True))
    op.add_column('production_orders', sa.Column('approved_by', sa.String(length=120), nullable=True))
    op.add_column('production_orders', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'approved_at')
    op.drop_column('production_orders', 'approved_by')
    op.drop_column('production_orders', 'order_no')
    # ### end Alembic commands ###
