"""pcr pir separation, mass balance fields, test method, live data period columns

Revision ID: 26fb93236845
Revises: 4aceb1353dfb
Create Date: 2026-08-30 18:24:34.820848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26fb93236845'
down_revision: Union[str, None] = '4aceb1353dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_tests', sa.Column('test_method', sa.String(length=160), nullable=True))
    op.add_column('production_live_data', sa.Column('period_produced_qty_units', sa.Integer(), nullable=False))
    op.add_column('production_live_data', sa.Column('cumulative_energy_kwh', sa.Float(), nullable=False))
    op.add_column('production_live_data', sa.Column('cumulative_waste_kg', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_live_data', 'cumulative_waste_kg')
    op.drop_column('production_live_data', 'cumulative_energy_kwh')
    op.drop_column('production_live_data', 'period_produced_qty_units')
    op.drop_column('physical_tests', 'test_method')
    # ### end Alembic commands ###
