"""e3_hammadde_kutuphanesi

Revision ID: 27daeb1b8dc3
Revises: e2f401f54500
Create Date: 2026-08-31 10:57:31.806250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27daeb1b8dc3'
down_revision: Union[str, None] = 'e2f401f54500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('currency', sa.String(length=10), nullable=False, server_default='TRY'))
    op.add_column('materials', sa.Column('origin_country', sa.String(length=80), nullable=True))
    op.add_column('materials', sa.Column('technical_datasheet_ref', sa.String(length=300), nullable=True))
    op.add_column('materials', sa.Column('compliance_documents_ref', sa.String(length=300), nullable=True))
    op.add_column('materials', sa.Column('post_consumer_content_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'post_consumer_content_pct')
    op.drop_column('materials', 'compliance_documents_ref')
    op.drop_column('materials', 'technical_datasheet_ref')
    op.drop_column('materials', 'origin_country')
    op.drop_column('materials', 'currency')
    # ### end Alembic commands ###
