"""l1_regulatory_decision_trail

Revision ID: 2831df27ef9a
Revises: 153414c62991
Create Date: 2026-09-01 19:16:01.083720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2831df27ef9a'
down_revision: Union[str, None] = '153414c62991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_assessments', sa.Column('decision_trail', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_assessments', 'decision_trail')
    # ### end Alembic commands ###
