"""c1 digital product passport

Revision ID: 2e1a862813c8
Revises: 3311b0b3e6c4
Create Date: 2026-08-31 02:41:42.380590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e1a862813c8'
down_revision: Union[str, None] = '3311b0b3e6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_product_passports',
    sa.Column('passport_no', sa.String(length=40), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('previous_passport_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_passport_id'], ['digital_product_passports.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digital_product_passports')
    # ### end Alembic commands ###
