"""f3_gida_temas_mevzuati

Revision ID: 3160b45f797a
Revises: 3748e36ce923
Create Date: 2026-08-31 20:54:58.235885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3160b45f797a'
down_revision: Union[str, None] = '3748e36ce923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_contact_requirements',
    sa.Column('regulation_id', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(length=40), nullable=False),
    sa.Column('substance', sa.String(length=160), nullable=True),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('limit_unit', sa.String(length=20), nullable=True),
    sa.Column('applies_to_pcr', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_contact_requirements')
    # ### end Alembic commands ###
