"""B4: additive library expansion (manufacturer, carrier, cost, carbon EF)

Revision ID: 322b5d98a252
Revises: 5c034658da61
Create Date: 2026-08-31 01:29:26.365366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '322b5d98a252'
down_revision: Union[str, None] = '5c034658da61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table + server_default: bkz. B.1/B.2 migration'larındaki
    # aynı SQLite notu (var olan tabloya FK eklenemez; NOT NULL yeni sütun
    # var olan satırlarda varsayılansız patlar).
    with op.batch_alter_table('additives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('carrier_polymer', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('regulatory_document_ref', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cost_per_kg', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('carbon_ef_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_additives_carbon_ef_id', 'carbon_emission_factors', ['carbon_ef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additives', schema=None) as batch_op:
        batch_op.drop_constraint('fk_additives_carbon_ef_id', type_='foreignkey')
        batch_op.drop_column('carbon_ef_id')
        batch_op.drop_column('cost_per_kg')
        batch_op.drop_column('regulatory_document_ref')
        batch_op.drop_column('carrier_polymer')
        batch_op.drop_column('manufacturer')
    # ### end Alembic commands ###
