"""b8 ppwr regulation requirement library

Revision ID: 3311b0b3e6c4
Revises: 0bf0280c7ea2
Create Date: 2026-08-31 02:15:29.353948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3311b0b3e6c4'
down_revision: Union[str, None] = '0bf0280c7ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_requirements',
    sa.Column('regulation_id', sa.String(), nullable=False),
    sa.Column('regulation_no', sa.String(length=60), nullable=False),
    sa.Column('article', sa.String(length=60), nullable=False),
    sa.Column('packaging_category', sa.String(length=80), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('requirement_text', sa.String(length=2000), nullable=False),
    sa.Column('pcr_only', sa.Boolean(), nullable=False),
    sa.Column('exception_text', sa.String(length=400), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('default_verdict', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulation_requirements')
    # ### end Alembic commands ###
