"""f2_f4_mevzuat_esik_kimyasal_kisitlar

Revision ID: 3748e36ce923
Revises: 6ecabbe7a1ba
Create Date: 2026-08-31 20:45:24.438042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3748e36ce923'
down_revision: Union[str, None] = '6ecabbe7a1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_restrictions',
    sa.Column('substance_group', sa.String(length=60), nullable=False),
    sa.Column('restriction_type', sa.String(length=60), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('limit_unit', sa.String(length=20), nullable=False),
    sa.Column('food_contact_only', sa.Boolean(), nullable=False),
    sa.Column('regulation_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('regulation_requirements', sa.Column('threshold_value', sa.Float(), nullable=True))
    op.add_column('regulation_requirements', sa.Column('threshold_unit', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_requirements', 'threshold_unit')
    op.drop_column('regulation_requirements', 'threshold_value')
    op.drop_table('chemical_restrictions')
    # ### end Alembic commands ###
