"""B5: product SKU library

Revision ID: 376fcbee2302
Revises: 322b5d98a252
Create Date: 2026-08-31 01:42:40.989174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '376fcbee2302'
down_revision: Union[str, None] = '322b5d98a252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_skus',
    sa.Column('sku_code', sa.String(length=60), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('packaging_type', sa.String(length=120), nullable=False),
    sa.Column('usage_area', sa.String(length=160), nullable=False),
    sa.Column('customer', sa.String(length=160), nullable=True),
    sa.Column('target_market', sa.String(length=120), nullable=False),
    sa.Column('food_contact', sa.Boolean(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('film_thickness_micron', sa.Float(), nullable=True),
    sa.Column('gsm', sa.Float(), nullable=True),
    sa.Column('layer_count', sa.Integer(), nullable=True),
    sa.Column('layer_structure', sa.String(length=40), nullable=True),
    sa.Column('line_id', sa.String(), nullable=True),
    sa.Column('current_recipe_id', sa.String(), nullable=True),
    sa.Column('technical_spec_ref', sa.String(length=300), nullable=True),
    sa.Column('physical_test_criteria', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_recipe_id'], ['recipes.id'], name='fk_product_skus_current_recipe_id', use_alter=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    # batch_alter_table: bkz. B.1/B.2/B.4 migration'larındaki aynı SQLite notu.
    with op.batch_alter_table('packaging_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_packaging_requests_sku_id', 'product_skus', ['sku_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packaging_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_packaging_requests_sku_id', type_='foreignkey')
        batch_op.drop_column('sku_id')
    op.drop_table('product_skus')
    # ### end Alembic commands ###
