"""g3_asama4_manuel_hat_ekleme

Revision ID: 47a81f71935c
Revises: cc26a06cc5de
Create Date: 2026-08-31 22:20:23.319748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47a81f71935c'
down_revision: Union[str, None] = 'cc26a06cc5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lines', sa.Column('component_line_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lines', 'component_line_ids')
    # ### end Alembic commands ###
