"""initial schema

Revision ID: 4aceb1353dfb
Revises: 
Create Date: 2026-08-30 15:58:57.892940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4aceb1353dfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additives',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('additive_type', sa.String(length=60), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('dosage_min_pct', sa.Float(), nullable=False),
    sa.Column('dosage_max_pct', sa.Float(), nullable=False),
    sa.Column('food_contact_eligible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaging_requests',
    sa.Column('packaging_type', sa.String(length=120), nullable=False),
    sa.Column('usage_area', sa.String(length=160), nullable=False),
    sa.Column('product', sa.String(length=160), nullable=False),
    sa.Column('target_market', sa.String(length=120), nullable=False),
    sa.Column('food_contact', sa.Boolean(), nullable=False),
    sa.Column('target_volume_units', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('spec_file_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polymers',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('base_properties', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('production_lines',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('layer_structure', sa.String(length=40), nullable=False),
    sa.Column('layer_count', sa.Integer(), nullable=False),
    sa.Column('min_micron', sa.Float(), nullable=False),
    sa.Column('max_micron', sa.Float(), nullable=False),
    sa.Column('min_gsm', sa.Float(), nullable=True),
    sa.Column('max_gsm', sa.Float(), nullable=True),
    sa.Column('line_speed_m_min', sa.Float(), nullable=False),
    sa.Column('supported_packaging_types', sa.JSON(), nullable=False),
    sa.Column('energy_kwh_per_kg', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulations',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('applicable_packaging_types', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('materials',
    sa.Column('polymer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('material_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=True),
    sa.Column('mfi_g_10min', sa.Float(), nullable=True),
    sa.Column('density_g_cm3', sa.Float(), nullable=True),
    sa.Column('degradation_factor', sa.Float(), nullable=False),
    sa.Column('food_contact_eligible', sa.Boolean(), nullable=False),
    sa.Column('max_recommended_ratio_pct', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('carbon_factor_kg_co2_per_kg', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['polymer_id'], ['polymers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('packaging_request_id', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packaging_request_id'], ['packaging_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('packaging_request_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_recipe_id', sa.String(), nullable=True),
    sa.Column('line_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('total_gsm', sa.Float(), nullable=True),
    sa.Column('total_micron', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['packaging_request_id'], ['packaging_requests.id'], ),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_assessments',
    sa.Column('packaging_request_id', sa.String(), nullable=False),
    sa.Column('regulation_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('reasoning', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packaging_request_id'], ['packaging_requests.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_material_compatibility',
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('max_ratio_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_candidates',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_finalist', sa.Boolean(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('justification_text', sa.String(length=1500), nullable=True),
    sa.Column('decision_basis', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_orders',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_qty_units', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_additives',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('additive_id', sa.String(), nullable=False),
    sa.Column('dosage_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['additive_id'], ['additives.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_evaluations',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('reason_text', sa.String(length=1000), nullable=False),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_layers',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('layer_index', sa.Integer(), nullable=False),
    sa.Column('layer_label', sa.String(length=10), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('ratio_pct', sa.Float(), nullable=False),
    sa.Column('thickness_micron', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_metrics',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('data_source_type', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustainability_results',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('per_1000_units', sa.JSON(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_tests',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('production_order_id', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('target_min', sa.Float(), nullable=True),
    sa.Column('target_max', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_live_data',
    sa.Column('production_order_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('produced_qty_units', sa.Integer(), nullable=False),
    sa.Column('material_consumption', sa.JSON(), nullable=False),
    sa.Column('line_speed_m_min', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('waste_kg', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_live_data')
    op.drop_table('physical_tests')
    op.drop_table('sustainability_results')
    op.drop_table('recipe_metrics')
    op.drop_table('recipe_layers')
    op.drop_table('recipe_evaluations')
    op.drop_table('recipe_additives')
    op.drop_table('production_orders')
    op.drop_table('optimization_candidates')
    op.drop_table('line_material_compatibility')
    op.drop_table('regulatory_assessments')
    op.drop_table('recipes')
    op.drop_table('optimization_runs')
    op.drop_table('materials')
    op.drop_table('regulations')
    op.drop_table('production_lines')
    op.drop_table('polymers')
    op.drop_table('packaging_requests')
    op.drop_table('additives')
    # ### end Alembic commands ###
