"""B3: recipe_additives layer_index

Revision ID: 5c034658da61
Revises: 682e51b32dec
Create Date: 2026-08-30 21:06:14.127324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c034658da61'
down_revision: Union[str, None] = '682e51b32dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_additives', sa.Column('layer_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_additives', 'layer_index')
    # ### end Alembic commands ###
