"""f5_f7_f8_polimer_proses_ambalaj_yapisi_referans

Revision ID: 61018e7fdebb
Revises: 3160b45f797a
Create Date: 2026-08-31 21:00:05.093307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61018e7fdebb'
down_revision: Union[str, None] = '3160b45f797a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_structure_references',
    sa.Column('structure_pattern', sa.String(length=40), nullable=False),
    sa.Column('typical_usage', sa.String(length=400), nullable=False),
    sa.Column('barrier_properties', sa.String(length=400), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_pattern')
    )
    op.create_table('process_references',
    sa.Column('process_type', sa.String(length=60), nullable=False),
    sa.Column('parameter_name', sa.String(length=60), nullable=False),
    sa.Column('typical_min', sa.Float(), nullable=True),
    sa.Column('typical_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polymer_technical_references',
    sa.Column('polymer_id', sa.String(), nullable=False),
    sa.Column('property_name', sa.String(length=60), nullable=False),
    sa.Column('typical_min', sa.Float(), nullable=True),
    sa.Column('typical_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['polymer_id'], ['polymers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polymer_technical_references')
    op.drop_table('process_references')
    op.drop_table('layer_structure_references')
    # ### end Alembic commands ###
