"""B2: PCR/PIR single-table inheritance, carbon emission factor library

Revision ID: 682e51b32dec
Revises: c9e94a7f5470
Create Date: 2026-08-30 20:55:43.657866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '682e51b32dec'
down_revision: Union[str, None] = 'c9e94a7f5470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_emission_factors',
    sa.Column('material_key', sa.String(length=160), nullable=False),
    sa.Column('ef_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('geography', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table: SQLite var olan bir tabloya FK constraint eklemeyi
    # doğrudan desteklemiyor (bkz. B.1 migration'ındaki aynı not).
    # server_default: NOT NULL yeni sütunlar (carbon_data_quality) var olan
    # satırlı tablolarda ADD COLUMN'da patlamasın diye.
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('certification_status', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('suitable_layer_position', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('tensile_strength_mpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('elongation_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dart_impact_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('melt_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processing_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additive_content_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('carbon_ef_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stock_qty_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lot_number', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('contamination_level', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('odor_level', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('technical_constraints', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('source_process', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('production_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('source_machine_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_recipe_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_materials_source_recipe_id', 'recipes', ['source_recipe_id'], ['id'])
        batch_op.create_foreign_key('fk_materials_source_machine_id', 'production_lines', ['source_machine_id'], ['id'])
        batch_op.create_foreign_key('fk_materials_carbon_ef_id', 'carbon_emission_factors', ['carbon_ef_id'], ['id'])

    with op.batch_alter_table('optimization_candidates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'carbon_data_quality', sa.String(length=20), nullable=False,
                server_default='tanimlanmadi',
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_candidates', schema=None) as batch_op:
        batch_op.drop_column('carbon_data_quality')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materials_carbon_ef_id', type_='foreignkey')
        batch_op.drop_constraint('fk_materials_source_machine_id', type_='foreignkey')
        batch_op.drop_constraint('fk_materials_source_recipe_id', type_='foreignkey')
        batch_op.drop_column('source_recipe_id')
        batch_op.drop_column('source_machine_id')
        batch_op.drop_column('production_date')
        batch_op.drop_column('source_process')
        batch_op.drop_column('technical_constraints')
        batch_op.drop_column('odor_level')
        batch_op.drop_column('contamination_level')
        batch_op.drop_column('lot_number')
        batch_op.drop_column('stock_qty_kg')
        batch_op.drop_column('carbon_ef_id')
        batch_op.drop_column('additive_content_note')
        batch_op.drop_column('processing_temp_c')
        batch_op.drop_column('melt_temp_c')
        batch_op.drop_column('dart_impact_g')
        batch_op.drop_column('elongation_pct')
        batch_op.drop_column('tensile_strength_mpa')
        batch_op.drop_column('suitable_layer_position')
        batch_op.drop_column('certification_status')
        batch_op.drop_column('color')
        batch_op.drop_column('supplier')
        batch_op.drop_column('manufacturer')
    op.drop_table('carbon_emission_factors')
    # ### end Alembic commands ###
