"""g1_asama2_acik_onay_ekrani

Revision ID: 68702d74bf62
Revises: b8290312153d
Create Date: 2026-08-31 21:55:40.543319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68702d74bf62'
down_revision: Union[str, None] = 'b8290312153d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packaging_requests', sa.Column('target_thickness_micron', sa.Float(), nullable=True))
    op.add_column('packaging_requests', sa.Column('target_gsm', sa.Float(), nullable=True))
    op.add_column('packaging_requests', sa.Column('physical_performance_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packaging_requests', 'physical_performance_notes')
    op.drop_column('packaging_requests', 'target_gsm')
    op.drop_column('packaging_requests', 'target_thickness_micron')
    # ### end Alembic commands ###
