"""g5_asama7_veri_kaynagi_enumu

Revision ID: 6afb147f493c
Revises: a1ca5e2576d6
Create Date: 2026-09-01 01:22:58.933035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6afb147f493c'
down_revision: Union[str, None] = 'a1ca5e2576d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('data_source_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'data_source_tags')
    # ### end Alembic commands ###
