"""e4_urun_portfoyu

Revision ID: 6d22bec14fff
Revises: 27daeb1b8dc3
Create Date: 2026-08-31 11:08:51.667419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d22bec14fff'
down_revision: Union[str, None] = '27daeb1b8dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('customer_sector', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 'customer_sector')
    # ### end Alembic commands ###
