"""f1_karbon_kutuphanesi_genisletme

Revision ID: 6ecabbe7a1ba
Revises: 6d22bec14fff
Create Date: 2026-08-31 20:36:38.581385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ecabbe7a1ba'
down_revision: Union[str, None] = '6d22bec14fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carbon_emission_factors', sa.Column('factor_type', sa.String(length=20), nullable=False, server_default='malzeme'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carbon_emission_factors', 'factor_type')
    # ### end Alembic commands ###
