"""g4_asama5_gercek_firma_hafizasi

Revision ID: a1ca5e2576d6
Revises: 47a81f71935c
Create Date: 2026-08-31 22:31:07.952710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1ca5e2576d6'
down_revision: Union[str, None] = '47a81f71935c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('reference_search_evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'reference_search_evidence')
    # ### end Alembic commands ###
