"""f9_geri_donusturulebilirlik_kriterleri

Revision ID: a1dbcecb5418
Revises: b16bd02c52d0
Create Date: 2026-08-31 21:12:01.355945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1dbcecb5418'
down_revision: Union[str, None] = 'b16bd02c52d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recyclability_criteria',
    sa.Column('packaging_category', sa.String(length=80), nullable=True),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('criterion_text', sa.String(length=500), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('regulatory_assessments', sa.Column('recyclability_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_assessments', 'recyclability_breakdown')
    op.drop_table('recyclability_criteria')
    # ### end Alembic commands ###
