"""c4 persist notable eliminated candidates

Revision ID: ae3d2e6dea5b
Revises: 2e1a862813c8
Create Date: 2026-08-31 08:22:54.538794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae3d2e6dea5b'
down_revision: Union[str, None] = '2e1a862813c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: mevcut satırlar için NOT NULL JSON sütunu, aynı B.1-C.1
    # migration'larındaki SQLite kısıtı — eski koşular "kaydedilmedi" yerine
    # dürüstçe boş liste ile okunur (rapor servisi bunu ayrıca metinle
    # işaretleyecek, bkz. C.5 planı).
    op.add_column(
        'optimization_runs',
        sa.Column('notable_eliminated', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimization_runs', 'notable_eliminated')
    # ### end Alembic commands ###
