"""f6_mekanik_test_standartlari

Revision ID: b16bd02c52d0
Revises: 61018e7fdebb
Create Date: 2026-08-31 21:06:44.081497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b16bd02c52d0'
down_revision: Union[str, None] = '61018e7fdebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanical_test_standards',
    sa.Column('test_type', sa.String(length=40), nullable=False),
    sa.Column('standard_name', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('packaging_category', sa.String(length=80), nullable=True),
    sa.Column('typical_min', sa.Float(), nullable=True),
    sa.Column('typical_max', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_demo_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mechanical_test_standards')
    # ### end Alembic commands ###
