"""B1: company facility root, machine park fields

Revision ID: c9e94a7f5470
Revises: 26fb93236845
Create Date: 2026-08-30 20:34:47.427465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9e94a7f5470'
down_revision: Union[str, None] = '26fb93236845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table kullanılıyor: SQLite var olan bir tabloya FK constraint
    # eklemeyi (create_foreign_key) doğrudan desteklemiyor -- batch mode bunu
    # kopyala-taşı stratejisiyle çözer, Postgres'te ise normal ALTER TABLE'a
    # düşer (iki dialekt için de doğru çalışır). NOT NULL boolean sütunlar için
    # server_default eklendi ki mevcut satırları olan bir tabloda ADD COLUMN
    # patlamasın (autogenerate bunu unutur).
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('process_type', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('extruder_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_width_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_dosage_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_dosage_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plc_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('opc_ua_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('modbus_tcp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('api_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_foreign_key('fk_production_lines_facility_id', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_production_lines_facility_id', type_='foreignkey')
        batch_op.drop_column('api_enabled')
        batch_op.drop_column('modbus_tcp_enabled')
        batch_op.drop_column('opc_ua_enabled')
        batch_op.drop_column('plc_enabled')
        batch_op.drop_column('max_dosage_pct')
        batch_op.drop_column('min_dosage_pct')
        batch_op.drop_column('max_width_mm')
        batch_op.drop_column('extruder_count')
        batch_op.drop_column('process_type')
        batch_op.drop_column('facility_id')
    op.drop_table('facilities')
    op.drop_table('companies')
    # ### end Alembic commands ###
