"""g2_asama3_5_durumlu_sonuc_modeli

Revision ID: cc26a06cc5de
Revises: 68702d74bf62
Create Date: 2026-08-31 22:07:21.873641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc26a06cc5de'
down_revision: Union[str, None] = '68702d74bf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_requirements', sa.Column('sub_article', sa.String(length=60), nullable=True))
    op.add_column('regulation_requirements', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_requirements', 'last_reviewed_at')
    op.drop_column('regulation_requirements', 'sub_article')
    # ### end Alembic commands ###
