"""e1 firma profili

Revision ID: df299e6faa69
Revises: 8bcd26372eb1
Create Date: 2026-08-31 10:27:52.028122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df299e6faa69'
down_revision: Union[str, None] = '8bcd26372eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('trade_name', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('tax_country', sa.String(length=80), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=80), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=300), nullable=True))
    op.add_column('companies', sa.Column('business_area', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('nace_code', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('annual_production_capacity_tons', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('annual_actual_production_tons', sa.Float(), nullable=True))
    # server_default: mevcut satırlar için NOT NULL JSON sütunu, aynı B.1-D.2
    # migration'larındaki SQLite kısıtı.
    op.add_column(
        'companies', sa.Column('main_export_markets', sa.JSON(), nullable=False, server_default='[]')
    )
    op.add_column('companies', sa.Column('exports_to_eu', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('produces_food_packaging', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('facilities', sa.Column('code', sa.String(length=40), nullable=True))
    op.add_column('facilities', sa.Column('production_area_m2', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('annual_capacity_tons', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('working_days_per_year', sa.Integer(), nullable=True))
    op.add_column('facilities', sa.Column('shift_count', sa.Integer(), nullable=True))
    op.add_column('facilities', sa.Column('working_hours_per_day', sa.Float(), nullable=True))
    op.add_column(
        'facilities', sa.Column('main_processes', sa.JSON(), nullable=False, server_default='[]')
    )
    op.add_column('facilities', sa.Column('electricity_consumption_kwh_year', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('gas_consumption_m3_year', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('renewable_energy_used', sa.Boolean(), nullable=True))
    op.add_column('facilities', sa.Column('renewable_energy_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'renewable_energy_pct')
    op.drop_column('facilities', 'renewable_energy_used')
    op.drop_column('facilities', 'gas_consumption_m3_year')
    op.drop_column('facilities', 'electricity_consumption_kwh_year')
    op.drop_column('facilities', 'main_processes')
    op.drop_column('facilities', 'working_hours_per_day')
    op.drop_column('facilities', 'shift_count')
    op.drop_column('facilities', 'working_days_per_year')
    op.drop_column('facilities', 'annual_capacity_tons')
    op.drop_column('facilities', 'production_area_m2')
    op.drop_column('facilities', 'code')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'produces_food_packaging')
    op.drop_column('companies', 'exports_to_eu')
    op.drop_column('companies', 'main_export_markets')
    op.drop_column('companies', 'annual_actual_production_tons')
    op.drop_column('companies', 'annual_production_capacity_tons')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'nace_code')
    op.drop_column('companies', 'business_area')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'tax_country')
    op.drop_column('companies', 'trade_name')
    # ### end Alembic commands ###
