"""e2 makine parki

Revision ID: e2f401f54500
Revises: df299e6faa69
Create Date: 2026-08-31 10:43:03.299559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2f401f54500'
down_revision: Union[str, None] = 'df299e6faa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lines', sa.Column('manufacturer', sa.String(length=160), nullable=True))
    op.add_column('production_lines', sa.Column('model', sa.String(length=160), nullable=True))
    op.add_column('production_lines', sa.Column('install_year', sa.Integer(), nullable=True))
    op.add_column('production_lines', sa.Column('nominal_capacity_kg_year', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('actual_capacity_kg_year', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('min_line_speed_m_min', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('max_line_speed_m_min', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('layer_structure_type', sa.String(length=20), nullable=True))
    op.add_column('production_lines', sa.Column('screw_diameter_mm', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('ld_ratio', sa.Float(), nullable=True))
    # server_default: mevcut satırlar için NOT NULL JSON sütunu, aynı B.1-E.1
    # migration'larındaki SQLite kısıtı.
    op.add_column(
        'production_lines', sa.Column('suitable_polymer_codes', sa.JSON(), nullable=False, server_default='[]')
    )
    op.add_column('production_lines', sa.Column('pcr_capable', sa.Boolean(), nullable=True))
    op.add_column('production_lines', sa.Column('pir_capable', sa.Boolean(), nullable=True))
    op.add_column('production_lines', sa.Column('max_pcr_technical_pct', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('max_pir_technical_pct', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('gravimetric_dosing_equipped', sa.Boolean(), nullable=True))
    op.add_column('production_lines', sa.Column('online_thickness_control', sa.Boolean(), nullable=True))
    op.add_column('production_lines', sa.Column('energy_metering_equipped', sa.Boolean(), nullable=True))
    op.add_column('production_lines', sa.Column('average_waste_rate_pct', sa.Float(), nullable=True))
    op.add_column('production_lines', sa.Column('availability_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lines', 'availability_status')
    op.drop_column('production_lines', 'average_waste_rate_pct')
    op.drop_column('production_lines', 'energy_metering_equipped')
    op.drop_column('production_lines', 'online_thickness_control')
    op.drop_column('production_lines', 'gravimetric_dosing_equipped')
    op.drop_column('production_lines', 'max_pir_technical_pct')
    op.drop_column('production_lines', 'max_pcr_technical_pct')
    op.drop_column('production_lines', 'pir_capable')
    op.drop_column('production_lines', 'pcr_capable')
    op.drop_column('production_lines', 'suitable_polymer_codes')
    op.drop_column('production_lines', 'ld_ratio')
    op.drop_column('production_lines', 'screw_diameter_mm')
    op.drop_column('production_lines', 'layer_structure_type')
    op.drop_column('production_lines', 'max_line_speed_m_min')
    op.drop_column('production_lines', 'min_line_speed_m_min')
    op.drop_column('production_lines', 'actual_capacity_kg_year')
    op.drop_column('production_lines', 'nominal_capacity_kg_year')
    op.drop_column('production_lines', 'install_year')
    op.drop_column('production_lines', 'model')
    op.drop_column('production_lines', 'manufacturer')
    # ### end Alembic commands ###
