"""l3_mevzuat_versiyon_gecmisi

Revision ID: e40892077f1a
Revises: 2831df27ef9a
Create Date: 2026-09-01 19:26:28.314326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e40892077f1a'
down_revision: Union[str, None] = '2831df27ef9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_requirements', sa.Column('previous_version', sa.String(length=20), nullable=True))
    op.add_column('regulation_requirements', sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('regulation_requirements', sa.Column('change_summary', sa.String(length=500), nullable=True))
    op.add_column('regulatory_assessments', sa.Column('regulation_version_snapshot', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_assessments', 'regulation_version_snapshot')
    op.drop_column('regulation_requirements', 'change_summary')
    op.drop_column('regulation_requirements', 'changed_at')
    op.drop_column('regulation_requirements', 'previous_version')
    # ### end Alembic commands ###
